CONTIKI_PROJECT = pa-router
all: $(CONTIKI_PROJECT)
CONTIKI = ../..
MODULES += os/services/shell


PROJECTDIRS += ../../pa
CONTIKI_SOURCEFILES += pa.c

include $(CONTIKI)/Makefile.include



